export const SET_TOKEN = 'SET_TOKEN';
export const SET_USERID = 'SET_USERID';
export const SET_USERDATA = 'SET_USERDATA';
export const USER_LOGOUT = 'USER_LOGOUT';
export const INIT_APPLICATION = 'INIT_APPLICATION';
export const CHANGE_INDEX_CATALOG = 'CHANGE_INDEX_CATALOG';
